<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="Repositories\**"/>
        <EmbeddedResource Remove="Repositories\**"/>
        <None Remove="Repositories\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.4"/>
        <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.4"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.11" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.11" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.4"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.4"/>
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="10.0.1"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Gems.TechSupport.Application\Gems.TechSupport.Application.csproj"/>
        <ProjectReference Include="..\Gems.TechSupport.Domain\Gems.TechSupport.Domain.csproj"/>
    </ItemGroup>

</Project>